import type { Metadata } from 'next'
import Navbar from "@/app/todos/Navbar";
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function TodoLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const token = cookies().get('token')?.value
  const isLogin = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/users/me`, {
    method: 'GET',
    headers: {
      'Authorization': 'Bearer ' + token
    }
  }).then(response => response.status == 200)

  if(!isLogin) redirect('/login')

  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className='max-w-5xl mt-4 mx-auto'>
          {children}
        </main>
      </body>
    </html>
  )
}
