import type { Metadata } from 'next'
import Navbar from "@/app/todos/Navbar";
import { cookies } from 'next/headers'
import { redirect } from 'next/navigation'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function TodoLayout({
  children
}: {
  children: React.ReactNode
}) {
  const token = cookies().get('token')?.value
  const authRes = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/api/v1/users/me`, {
    method: 'GET',
    headers: {
      'Authorization': 'Bearer ' + token
    }
  })

  if(authRes.status != 200) redirect('/login')

  const user = await authRes.json()

  return (
    <html lang="en">
      <head>
        
      </head>
      <body>
        <Navbar name={user.name} email={user.email} />
        <main className='max-w-5xl mt-4 mx-auto px-4'>
          {children}
        </main>
      </body>
    </html>
  )
}
